### ISSUE TITLE
Bug in QInputBase

### ISSUE THREAD

**Issue by docm64** [justpy-org/justpy#255]
In QInputBase, the attributes slots[] and evaluate_prop[] are defined as class members, while IMHO they have to be instance members. I stumbled into it when I created a webpage containing a QDate component which has a JS function assigned to its 'options' attribute. And also containing a QSelect component the 'options' attribute of which is a string. Very strange things happened...

I solved the problem by changing the source code of QInputBase.
I deleted line 56 ```evaluate_prop = []```
I added a line at the end of the```__init__()``` method, line 66 ```self.evaluate_prop = []```

Looking at the source code of QInputBase, I believe the same kind of issue exists with the slots[] property. As I am not using it in my project, I didn't touch it though.

**Comment by elimintz** [comment]
Yes, good point, thank you. I will change it.

**Comment by WolfgangFahl** [comment]
The lines are not at the positions mentioned any more.
```python
class _QInputBase(Input):

    slots = []
    evaluate_prop = []

    def __init__(self, **kwargs):
        self.disable_input_event = False
        super().__init__(**kwargs)
        self.vue_type = 'quasar_component'
        self.directives = quasar_directives
        self.disable_events = False
        self.prop_list = []
        self.attributes = []
```

**Comment by WolfgangFahl** [comment]
Has the code such as quasarcomponents been written completely manual or has there been some kind of (semi-) automation/generator technology to so?

**Comment by elimintz** [comment]
It was written manually using the copy and paste technique.

**Comment by WolfgangFahl** [comment]
@elimintz that is good to know. My background is in model driven development and generator technology. It was a big hype between 1996 and 2008 and is not much applied in the industry any more. At least it will be worthwhile to do an analysis how systematic the problem ist and what the rules are. Automation requires systematization. 

@docm64  since a systematic/general solution will take it's time could you provide a pull request for this?
