### ISSUE TITLE
Defining a javascript function for onclick?

### ISSUE THREAD

**Issue by aalexei** [justpy-org/justpy#394]
How would I create an element that defines a javascript function for the onclick event? i.e. force an element to output something like:
```html
<div onclick="alert('hello again')">hello</div>
```

I'm not after a python callback, and I know I can do the above with inner_html, but I'm after adding a javascript function to an existing jp element.

**Comment by sandeep-gh** [comment]
All the events on the browser are tied to the justpy event handler on browser side. They marshall the event info and send to the python via websockets. That is the design. You can add additional div elements in main.html  (or any of the included js file) but those html elements would be outside of the justpy ecosystem.

**Comment by aalexei** [comment]
Yeah, I realise that the resulting event would be outside juspy ecosystem. Here's the issue: it doesn't't seem possible to use the javascript clipboard API on Safari outside a user event.

So this will work on all browsers:
```
<div onclick="navigator.clipboard.writeText('Hello again')">hello</div>
```

but if I bind the event in justpy to a python function, and call clipboard,writeText using  run_javascript() it will *not* work on Safari (works on Chrome and Firefox). I'm trying to support all browsers and defining a js onclick function seems the easiest way if there was some way to do it. I can do it with inner_html but this is super messy to style for things like menu items etc. I'd have to manually replicate the quasar structures that are generated by QBtn etc.

**Comment by WolfgangFahl** [comment]
The ideas is to allow arbitrary javascript functions to be added via a directory that holds the code instead of using the header text workaround that is currently inplace. Then it would be necessary to have custom links between events and such javascript code which in principle just means that we make the remote DOM rewriting process more systematic then it is right now. Unfortunately this issue will have to wait for a future milestone.

**Comment by WolfgangFahl** [comment]
see #685
