### ISSUE TITLE
Outdated version of Quasar when served with NO_INTERNET

### ISSUE THREAD

**Issue by rodja** [justpy-org/justpy#460]
JustPy still provides the outdated Quasar 1.9.14: https://github.com/elimintz/justpy/blob/72f94a9f1e7fcd2734b3c947ba2e830387083698/justpy/templates/local/quasar.js#L2.

The latest Quasar version is 2.7.7 which has many more features and bugfixes. I suggest we update the locally provided Quasar to the latest stable version.

**Comment by rodja** [comment]
@elimintz have you just copied the files as generated by https://quasar.dev/start/umd? Is that the right approach for an update?

**Comment by WolfgangFahl** [comment]
```bash
wget https://cdn.jsdelivr.net/npm/quasar@2.7.7/dist/quasar.umd.prod.js
```

**Comment by WolfgangFahl** [comment]
How would i activate NO_INTERNET in a test?

**Comment by elimintz** [comment]
Quasar version 2 works only with Vue 3 and justpy uses Vue 2 so we have to use version 1 of Quasar.
However, the good news is that when a feature is added to Quasar 2, it usually find its way to Quasar 1 also. I guess many projects that use Quasar are in the same situation as us. 

So we should provide the latest Quasar 1 version which is 1.19.5

**Comment by rodja** [comment]
@elimintz What would it take to port JustPy to Vue 3? Are there any benefits or is it just very incompatible?

**Comment by elimintz** [comment]
The Vue components for me were the most difficult things to develop by far. I went through several design iterations. Justpy uses Vue in an original way, that as far as I can tell, no one used before.

This is the list of breaking changes between Vue 2 and Vue 3: https://v3-migration.vuejs.org/breaking-changes/

After reading it, I decided that I didn't have the appetite to take on the migration effort since for almost all users, they will not notice any difference. and it would be a very time consuming effort.

**Comment by rodja** [comment]
Ok. What do you think about the [Vue 3 migration build](https://v3-migration.vuejs.org/migration-build.html)? It looks like we may run Vue 2 code on Vue 3 with this...

**Comment by elimintz** [comment]
Not sure this is an option for us because we don't build the application, justpy templates download the cdn version.

**Comment by WolfgangFahl** [comment]
For milestone 0.7 it would be good to have the latest compatible version.

**Comment by WolfgangFahl** [comment]
see #685
