### ISSUE TITLE
Replace Cookie handling with middleware

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#535]
### Discussed in https://github.com/justpy-org/justpy/discussions/529

<div type='discussions-op-text'>

<sup>Originally posted by **WolfgangFahl** September 13, 2022</sup>
The signed cookie handling is a standard infrastructure problem that we might want to use from a library instead of doing
the current "roll your own cookie handling". Unfortunately https://fastapi.tiangolo.com/advanced/response-cookies/ doesn't linke to any libraries

We need to find a proper library for this. Candidates might be:
* https://github.com/klen/asgi-sessions
* https://github.com/thearchitector/starlette-securecookies
* https://asgi-signing-middleware.hackan.net/en/stable/cookie/</div>

**Comment by WolfgangFahl** [comment]
the starting point would be just two new lines

```python
#@TODO     
#if SESSIONS:
#    middleware.append(Middleware(SessionMiddleware, secret_key=SECRET_KEY))
```
changing the docs will be more work.
For a start we could change the secret key default to:
SECRET_KEY = config(
    "SECRET_KEY", default=f"$$$justpy_random_secret_key_{secrets.token_hex(32)}$$$"
)

**Comment by WolfgangFahl** [comment]
https://asgi-signing-middleware.hackan.net/en/stable/cookie/ is a candidate for the cookie handling

**Comment by sandeep-gh** [comment]
Nice clean library. Don't see much issues then directly linking as dependency and updating the docs.

**Comment by elimintz** [comment]
Since most people are not expert on cookie security I think that whatever method is used, the defaults should be ones that are recommended here:
https://blog.miguelgrinberg.com/post/cookie-security-for-flask-applications

My initial thought when designing this is that the cookie will only be the session id and would be an http only cookie. It didn't seem that we need a dedicated library for this. 

If just the session id is in the cookie, the asgi signing middleware my be an overkill. From its docs:
"Use this middleware if you want to store certain complex data structures into a cookie. Note that this middleware is slower than the SimpleSignedCookieMiddleware, but ideal for any kind of data structure."

Starlette has the following middleware out of the box: https://www.starlette.io/middleware/#sessionmiddleware
I am not sure it covers all out needs, but is a good option to explore.

**Comment by sandeep-gh** [comment]
The starlette sessions middleware seems equivalent to SimpleSignedCookieMiddleware. The ASGI signing middleware will allow you to specify the cookie data type. This might be an overkill. Can't see a use case for that. 

Sticking with SessionMiddleware seems ok to me if all that is required is a signed dictionary to be stored in cookie.

**Comment by sandeep-gh** [comment]
Had a closer look at SessionMiddlewar. It is bit too restrictive and the code is not very clear. The current implementation in justpy seems just right. Easy to follow, flexible and does the job. I would to leave that implementation as is.

**Comment by WolfgangFahl** [comment]
If we keep things at they are this ticket would only be about the option to switch to a different middleware and still have justpy working properly.

**Comment by sandeep-gh** [comment]
I have the feeling the most users will opt for justpy way of using cookies. If we refactor cookie signing part to allow for another middleware to be plugged in then Justpy still will needs some mechanism to hold session_id in cookie. 

Seems to me that refactoring could get messy.

**Comment by WolfgangFahl** [comment]
see #685
