### ISSUE TITLE
Improve mountall in demobrowser

### ISSUE THREAD

**Issue by byzakyz** [justpy-org/justpy#584]
1. add 2 select fields for range (eg. selecting 1 to 220)
2. mount only demos in range
3. do binary search to find broken example causing display of highcharts parliament visualisation

**Comment by WolfgangFahl** [comment]
use http://v0-13.quasar-framework.org/components/numeric.html?

**Comment by byzakyz** [comment]
Binary Search:

first and second half 1- 110 and 111 - 220
if problem in first half: split here
if problem in second half: split here

max number of steps: log2(220) = ~8

Negative approach :
we are actually searching for the working ones

**Comment by byzakyz** [comment]
as next step add status as attribute to examples.json entries only for the ones that are not working.

**Comment by byzakyz** [comment]
created a slider with range. Found example number 130 as the one cousing the problem.

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/200109998-faa02453-3cf2-4a14-8a6b-1b9a290e343f.png)
 looks good.
 
 
![grafik](https://user-images.githubusercontent.com/1336221/200110013-5c8db5e6-62c6-4398-b1bb-69f39fd384bd.png)
 also helps. Now we need to make sure that examples that break other examples are not mounted by default but only when explictly asking to do this. 
 
  _example number 130 as the one causing the problem_ -> please give the id/name of the examples since the numbers change when new examples such as #589  are added.
